# Generated by Django 4.0.1 on 2022-02-01 17:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import post.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Tag',
                'db_table': 'tags',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, unique=True, verbose_name='Post title')),
                ('text', models.TextField(verbose_name='Post data')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Post created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Post update')),
                ('is_moderated', models.BooleanField(default=False)),
                ('views', models.BigIntegerField(default=0)),
                ('image', models.ImageField(upload_to=post.models.Post.file_path)),
                ('url', models.SlugField(max_length=256, unique=True, verbose_name='Link to Post')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='Post author')),
                ('tags', models.ManyToManyField(related_name='posts', to='post.Tag')),
            ],
            options={
                'verbose_name': 'Post',
                'db_table': 'posts',
            },
        ),
    ]
