# Generated by Django 4.0.1 on 2022-02-01 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-id',), 'verbose_name': 'Post'},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='url',
            new_name='slug',
        ),
    ]
